loc: "upper center"
bbox_to_anchor: [0.45, 0.91]
fancybox: true
ncol: 2
labelspacing: 1.5
framealpha: 1
shadow: true
borderpad: 1
frameon: true
edgecolor: "black"
facecolor: "white"
fontsize: 15
